return {
    ['ScreenGui'] = Instance.new("ScreenGui"),
    
    ['Frame'] = Instance.new("Frame"),
    ['Frame_2'] = Instance.new("Frame"),
    ['Frame_3'] = Instance.new("Frame"),
    ['Frame_4'] = Instance.new("Frame"),
    ['Frame_5'] = Instance.new("Frame"),
    ['Frame_6'] = Instance.new("Frame"),

    ['ImageLabel'] = Instance.new("ImageLabel"),
    ['ImageLabel_2'] = Instance.new("ImageLabel"),
    ['ImageLabel_3'] = Instance.new("ImageLabel"),
    ['ImageLabel_4'] = Instance.new("ImageLabel"),
    ['ImageLabel_5'] = Instance.new("ImageLabel"),
    ['ImageLabel_6'] = Instance.new("ImageLabel"),
    ['ImageLabel_7'] = Instance.new("ImageLabel"),
    ['ImageLabel_8'] = Instance.new("ImageLabel"),
    ['ImageLabel_9'] = Instance.new("ImageLabel"),
    ['ImageLabel_10'] = Instance.new("ImageLabel"),
    ['ImageLabel_11'] = Instance.new("ImageLabel"),
    ['ImageLabel_12'] = Instance.new("ImageLabel"),

    ['Shadow'] = Instance.new("ImageLabel"),
    ['Shadow_2'] = Instance.new("ImageLabel"),
    ['Shadow_3'] = Instance.new("ImageLabel"),
    ['Shadow_4'] = Instance.new("ImageLabel"),
    ['Shadow_5'] = Instance.new("ImageLabel"),
    
    ['UIAspectRatioConstraint'] = Instance.new("UIAspectRatioConstraint"),
    ['UIAspectRatioConstraint_2'] = Instance.new("UIAspectRatioConstraint"),
    ['UIAspectRatioConstraint_3'] = Instance.new("UIAspectRatioConstraint"),
    ['UIAspectRatioConstraint_4'] = Instance.new("UIAspectRatioConstraint"),
    ['UIAspectRatioConstraint_5'] = Instance.new("UIAspectRatioConstraint"),
    ['UIAspectRatioConstraint_6'] = Instance.new("UIAspectRatioConstraint"),

    ['UICorner'] = Instance.new("UICorner"),
    ['UICorner_2'] = Instance.new("UICorner"),
    ['UICorner_3'] = Instance.new("UICorner"),
    ['UICorner_4'] = Instance.new("UICorner"),
    ['UICorner_5'] = Instance.new("UICorner"),
    ['UICorner_6'] = Instance.new("UICorner"),

    ['TextLabel'] = Instance.new("TextLabel"),
    ['TextLabel_2'] = Instance.new("TextLabel"),
    ['TextLabel_3'] = Instance.new("TextLabel"),
    ['TextLabel_4'] = Instance.new("TextLabel"),
    ['TextLabel_5'] = Instance.new("TextLabel"),
    ['TextLabel_6'] = Instance.new("TextLabel"),
    ['TextLabel_7'] = Instance.new("TextLabel"),
    ['TextLabel_8'] = Instance.new("TextLabel"),
    ['TextLabel_9'] = Instance.new("TextLabel"),
    ['TextLabel_10'] = Instance.new("TextLabel"),
    ['TextLabel_11'] = Instance.new("TextLabel"),
    ['TextLabel_12'] = Instance.new("TextLabel"),
    ['TextLabel_13'] = Instance.new("TextLabel"),
    ['TextLabel_14'] = Instance.new("TextLabel"),
    ['TextLabel_15'] = Instance.new("TextLabel"),
    ['TextLabel_16'] = Instance.new("TextLabel"),
    ['TextLabel_17'] = Instance.new("TextLabel"),
    ['TextLabel_18'] = Instance.new("TextLabel"),
    ['TextLabel_19'] = Instance.new("TextLabel"),
    ['TextLabel_20'] = Instance.new("TextLabel"),
    ['TextLabel_21'] = Instance.new("TextLabel"),
    
    ['TextButton'] = Instance.new("TextButton"),
    ['TextButton_2'] = Instance.new("TextButton"),
    ['TextButton_3'] = Instance.new("TextButton"),
}
